### ISSUE TITLE
Could not find 'bundler' (2.1.4)

### ISSUE THREAD

**Issue by guettli** [unpoly/unpoly-site#7]
I want to fix https://github.com/unpoly/unpoly/issues/144#issuecomment-740446414

 I followed the installation instructions, but this failed with this error:

Sorry, I am new to ruby.

```
guettli@yoga15:~/projects/unpoly-site$ middleman server
Traceback (most recent call last):
	4: from /usr/local/bin/middleman:23:in `<main>'
	3: from /usr/local/bin/middleman:23:in `load'
	2: from /var/lib/gems/2.7.0/gems/middleman-cli-4.2.1/bin/middleman:3:in `<top (required)>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- middleman-core/profiling (LoadError)
	10: from /usr/local/bin/middleman:23:in `<main>'
	 9: from /usr/local/bin/middleman:23:in `load'
	 8: from /var/lib/gems/2.7.0/gems/middleman-cli-4.2.1/bin/middleman:3:in `<top (required)>'
	 7: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	 6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:161:in `rescue in require'
	 5: from /usr/lib/ruby/2.7.0/rubygems.rb:209:in `try_activate'
	 4: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1373:in `activate'
	 3: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1391:in `activate_dependencies'
	 2: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1391:in `each'
	 1: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1402:in `block in activate_dependencies'
/usr/lib/ruby/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'bundler' (2.1.4) required by your /home/guettli/projects/unpoly-site/Gemfile.lock. (Gem::MissingSpecVersionError)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
Checked in 'GEM_PATH=/home/guettli/.gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0', execute `gem env` for more information
	11: from /usr/local/bin/middleman:23:in `<main>'
	10: from /usr/local/bin/middleman:23:in `load'
	 9: from /var/lib/gems/2.7.0/gems/middleman-cli-4.2.1/bin/middleman:3:in `<top (required)>'
	 8: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	 7: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:161:in `rescue in require'
	 6: from /usr/lib/ruby/2.7.0/rubygems.rb:208:in `try_activate'
	 5: from /usr/lib/ruby/2.7.0/rubygems.rb:215:in `rescue in try_activate'
	 4: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1373:in `activate'
	 3: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1391:in `activate_dependencies'
	 2: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1391:in `each'
	 1: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1402:in `block in activate_dependencies'
/usr/lib/ruby/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'bundler' (2.1.4) required by your /home/guettli/projects/unpoly-site/Gemfile.lock. (Gem::MissingSpecVersionError)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
Checked in 'GEM_PATH=/home/guettli/.gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0', execute `gem env` for more information
```

**Comment by adam12** [comment]
You probably only have bundler v1. If you install v2, it _should_ work.

`gem install bundler -v '~> 2'`

**Comment by triskweline** [comment]
If @guettli installed a fresh Ruby, he might not have any version of the bundler gem. We should add that to the README.

**Comment by adam12** [comment]
@guettli If you're still stuck, I ended up running into this even with the correct bundler version installed. So you might need to use `bundle exec` in front of `middleman serve`.

**Comment by guettli** [comment]
@adam12 thank you. Using `bundle exec middleman server` starts the server.

I created a PR for the README: https://github.com/unpoly/unpoly-site/pull/9
